name: envDP
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
  - pyg
dependencies:
  - python=3.11.6
  - pytorch=2.1.0
  - pip
  - cpuonly
  - pybind11=2.11.1
  - pytest
  - pip:
    - torch_geometric==2.4.0
    - gymnasium==0.29.1
    - tianshou==0.5.1